# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0004_tipousuario_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materia.TipoUsuario'),
        ),
    ]
