# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0006_userprofile_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradoNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Grado')),
            ],
        ),
    ]
