# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0007_gradonivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materia.GradoNivel'),
        ),
    ]
