# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 02:08
from __future__ import unicode_literals

import apps.materia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0009_temas'),
    ]

    operations = [
        migrations.AddField(
            model_name='temas',
            name='photo',
            field=models.ImageField(null=True, upload_to=apps.materia.models.Temas.url),
        ),
    ]
