# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 03:05
from __future__ import unicode_literals

import apps.materia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0010_temas_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='photo',
            field=models.ImageField(null=True, upload_to=apps.materia.models.Materia.url),
        ),
    ]
