# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:46
from __future__ import unicode_literals

import apps.materia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0011_materia_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('photo', models.ImageField(null=True, upload_to=apps.materia.models.ContentTema.url)),
                ('video', models.URLField()),
                ('tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materia.Temas')),
            ],
        ),
    ]
