# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0012_contenttema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttema',
            name='tema',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materia.Temas'),
        ),
    ]
